name: Gerar Documentação do Repositório

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gerar-documentacao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar Dependências Python
        run: |
          pip install pyyaml
          pip install PyGithub

      - name: Verificar Existência do Diretório "scripts"
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/.github/scripts" ]; then
            echo "Diretório scripts não encontrado, baixando o repositório novamente."
            rm -rf $GITHUB_WORKSPACE
            git clone https://github.com/elias-knt/foxter-mkt-campaign.git $GITHUB_WORKSPACE
          fi

      - name: Verificar Existência do Script Python
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/.github/scripts/gerar_documentacao.py" ]; then
            echo "Script Python para gerar documentação não encontrado."
            exit 1
          fi

      - name: Executar Script Python para Gerar Documentação
        env:
          GITHUB_TOKEN: ${{ secrets.CRIA_DOCUMENTACAO }}
        run: python $GITHUB_WORKSPACE/.github/scripts/gerar_documentacao.py

      - name: Adicionar, Confirmar e Empurrar Arquivos Gerados
        run: |
          git config --global user.email "elias.andrade@konecty.com"
          git config --global user.name "GitHub Actions"
          git add documentation/*
          git commit -m "Adicionar documentação gerada"
          git push origin main
