name: Gerar Documentação do Repositório

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gerar-documentacao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar Dependências Python
        run: |
          pip install pyyaml
          pip install PyGithub

      - name: Verificar Existência do Diretório "scripts"
        run: test -d $GITHUB_WORKSPACE/.github/scripts || echo "Diretório scripts não encontrado, baixando o repositório novamente."
        continue-on-error: true

      - name: Baixar Repositório Novamente se Falhar
        if: ${{ failure() }}
        run: rm -rf $GITHUB_WORKSPACE && git clone https://github.com/elias-knt/foxter-mkt-campaign.git $GITHUB_WORKSPACE

      - name: Verificar Existência do Script Python
        run: test -f $GITHUB_WORKSPACE/.github/scripts/gerar_documentacao.py
        continue-on-error: true

      - name: Executar Script Python para Gerar Documentação
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.CRIA_DOCUMENTACAO }}
        run: python $GITHUB_WORKSPACE/.github/scripts/gerar_documentacao.py

      - name: Adicionar, Confirmar e Empurrar Arquivos Gerados
        if: success()
        run: |
          git config --global user.email "elias.andrade@konecty.com"
          git config --global user.name "GitHub Actions"
          git add documentation/*
          git commit -m "Adicionar documentação gerada"
          git push origin main
